import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import Header from "@/components/Header"; // <-- Import Header
import { SolanaProvider } from "@/components/solana/solana-provider";
import { AuthProvider } from "@/context/auth-context";
import React from "react";
import "./globals.css";
import { ReactQueryProvider } from "./react-query-provider";

export const metadata = {
  title: "Shinzoku",
  description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
  { label: "Account", path: "/account" },
  { label: "Clusters", path: "/clusters" },
  { label: "Basic Program", path: "/basic" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <AuthProvider>
                <>
                  <Header /> {/* Render the header with disconnect button */}
                  {children}
                </>
              </AuthProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
